---
- hosts: all
  connection: local

  roles:
    - role: apt
      become: yes
    - role: install-vscode
      become: yes
    - role: install-balena-etcher
      become: yes
    - role: snaps
      become: yes
    - role: pip
    - role: geerlingguy.dotfiles
    - role: shell_setup

  tasks: []

  vars:
    vscode_extensions:
      - ms-python.python
      - ms-vscode.powershell
      - vscoss.vscode-ansible
      - ms-azuretools.vscode-docker
      - ms-vscode.go
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - redhat.vscode-yaml
