---
- name: Apt update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install other desirable apt packages
  apt:
    name:
      - git
      - net-tools
      - vim
      - zsh
      - gnome-tweaks
      - wireguard
      - python3-pip
    state: present
