---
- name: Trust bintray.com GPG key for installing Etcher
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61
    state: present

- name: Add Balena Etcher repo
  apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    filename: balena-etcher
    state: present

- name: Apt update cache
  apt:
    update_cache: yes
    cache_valid_time: "3600"

- name: Install Balena Etcher from Deb
  apt:
    name: balena-etcher-electron
