---
- name: Install snaps with option --classic
  snap:
    name:
      - kubectl
      - helm
    classic: yes
    state: present

- name: Install non classic snaps
  snap:
    name:
      - spotify
    state: present
