---
- name: Install snaps with option --classic
  snap:
    name: 
      - code
      - kubectl
      - helm
      - google-cloud-sdk
    classic: yes
    state: present

- name: Install non classic snaps
  snap:
    name:
      - spotify
    state: present
